### ISSUE TITLE
Run dotnet interactive through https

### ISSUE THREAD

**Issue by PawelStadnicki** [colombod/dotnet-interactive-experiments#2]
Hi @colombod & @jonsequitur, I'm trying to write a much more advanced application based on this repo.

Just wanted to ask if you or your team encountered a problem with running dotnet interactive through/without https/wss.

If I have a computer working on the corporate network there is a high chance that WebSockets will be blocked on Firewall and making DNI via HTTP on secure connection may solve the problem.
Is there any (easy) way/config to run dotnet interactive cli on https (wss) ? Or it requires full SSL setup (certificates) etc.

How you set up it for dotnettry or similar ? it is standard dotnet interactive HTTP or you customize you kestrel more gently (IIS reverse proxy to kestrel)? I know that the entry point for the DNI is CommandLineParser.cs but wonder if you have any sample in possession that shows how to run DNI on IIS or any other full-fledged hosting.

My goal is not only to make dotnet interactive work on secure connection but deploy it as a separate Virtual Network service

**Comment by PawelStadnicki** [comment]
Tmr I will try ommit all those issues with Azure Application Gateway

**Comment by colombod** [comment]
I think is better to move this conversation over to the official dotnet-interactive repo or the discord channel. I am not an expert when it comes to the kestrel + https part. deploy as network service is interesting !
